services:
  - type: web
    name: friendsync
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 --bind 0.0.0.0:$PORT "app:create_app()"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: SESSION_TYPE
        value: filesystem
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "true"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false